@startuml
actor User
participant ":Ui" as Ui
participant ":InternTrack" as InternTrack

User -> Ui : list
Ui->InternTrack : handleListCommand()
activate InternTrack
InternTrack -->Ui
deactivate InternTrack
Ui --> User

@enduml