@startuml
hide footbox

participant ":InternTrack" as InternTrack
participant ":Storage" as Storage
participant ":Ui" as Ui

[-> InternTrack : handleCommand("undo", userApplications, undoHistory)
activate InternTrack

InternTrack -> InternTrack : handleUndoCommand(userApplications, undoHistory)
activate InternTrack

InternTrack -> Storage : saveApplications(userApplications)
activate Storage
Storage --> InternTrack
deactivate Storage

InternTrack -> Ui : printUndoSuccess()
activate Ui
Ui --> InternTrack
deactivate Ui

deactivate InternTrack
[<-- InternTrack
deactivate InternTrack
@enduml